export {Homepage} from "./Home/Homepage"
export {ProductsList} from "./Products/ProductsList"
export {ProductDetail} from "./ProductDetail"
export {Register} from "./Register"
export {Login} from "./Login"
export {CartPage} from './Cart/CartPage'
export {OrderPage} from "./Order/OrderPage"
export {DashboardPage} from "./Dashboard/DashboardPage"
export {PageNotFound} from "./NotFound"